# version: "3"

# services:
#   app:
#     image: my-app:latest
#     build: .
#     environment:
#       - DISPLAY=${DISPLAY}
#     volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix
#     network_mode: host


version: "3"

services:
  app:
    image: my-app:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
    environment:
      PULSE_SERVER: unix:/run/user/1000/pulse/native
    volumes:
      - ~/.pulse:/home/developer/.pulse
      - ~/.config/pulse/cookie:/home/developer/.config/pulse/cookie
